# Generated by Django 4.1.6 on 2023-03-04 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=1500, verbose_name='Содержание')),
                ('image', models.FileField(upload_to='blog/', verbose_name='Изображение')),
                ('views', models.IntegerField(verbose_name='Кол-во просмотров')),
                ('published_data', models.DateField(default=datetime.date(2023, 3, 4), verbose_name='Дата')),
            ],
        ),
    ]
