# Generated by Django 4.1.6 on 2023-03-04 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=250, verbose_name='Отчество')),
                ('email', models.CharField(max_length=250, verbose_name='Почта')),
                ('comment', models.CharField(max_length=250, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='DistributionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True, verbose_name='Время рассылки')),
                ('date', models.DateField(default=datetime.date(2023, 3, 4), verbose_name='Дата')),
                ('periodicity', models.CharField(choices=[('day', 'день'), ('week', 'неделя'), ('month', 'месяц')], default='day', max_length=10, verbose_name='Период')),
                ('status', models.CharField(choices=[('created', 'создано'), ('launched', 'запущено'), ('completed', 'завершено')], default='created', max_length=10, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=250, verbose_name='тема')),
                ('text', models.CharField(max_length=250, verbose_name='текст')),
            ],
        ),
    ]
